import type { Metadata } from "next";
import "@styles/global.css";
import { RootLayout } from "@/layouts/root";


export const metadata: Metadata = {
  title: "Nathan Healea",
  description: "Generated by create next app",
};

export default RootLayout
